-- ============================================================================
-- Brokole - the rest of the ERP schema
--
-- Run with:  php api/migrate.php
--
-- Everything the app needs a database for that didn't have one yet:
--   1. Subscriptions   plans, subscriptions, schedule, pauses, invoices
--   2. Recipes         the link between a menu item and its ingredients
--   3. Procurement     vendors, purchase orders, goods receipts, bills
--   4. Production      daily plan + kitchen tickets
--   5. Payments & tax  payments, refunds, tax rates, customer invoices
--   6. Delivery        zones, rider assignments
--   7. Nutrition       customer goals, macro targets, meal log
--
-- Conventions, same as the rest of the schema:
--   money  DECIMAL(12,2), never a float
--   ids    CHAR(36) UUIDs generated by the API
--   time   created_at / updated_at on everything, soft delete where it matters
--   stock  append-only ledgers; on-hand and cost are DERIVED, never stored
-- ============================================================================

SET NAMES utf8mb4;

-- ═══════════════════════════════════════════════════════════════════════════
-- 1 · SUBSCRIPTIONS
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS plans (
  id              CHAR(36)      NOT NULL PRIMARY KEY,
  slug            VARCHAR(96)   NOT NULL UNIQUE,
  name            VARCHAR(160)  NOT NULL,
  description     TEXT,
  -- How many delivery days the plan buys, and over what period.
  billing_period  ENUM('weekly','monthly') NOT NULL DEFAULT 'weekly',
  meals_per_day   TINYINT UNSIGNED NOT NULL DEFAULT 1,
  days_included   SMALLINT UNSIGNED NOT NULL DEFAULT 7,
  price           DECIMAL(12,2) NOT NULL,
  -- Discount vs buying the same meals à la carte, for display only.
  discount_pct    DECIMAL(5,2)  NOT NULL DEFAULT 0,
  is_active       TINYINT(1)    NOT NULL DEFAULT 1,
  sort_order      INT           NOT NULL DEFAULT 0,
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at      DATETIME      NULL,
  CONSTRAINT plans_price_chk CHECK (price >= 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS subscriptions (
  id             CHAR(36)     NOT NULL PRIMARY KEY,
  subscription_no VARCHAR(32) NOT NULL UNIQUE,
  user_id        CHAR(36)     NOT NULL,
  plan_id        CHAR(36)     NOT NULL,
  outlet_id      CHAR(36)     NOT NULL,
  address_id     CHAR(36)     NULL,
  status         ENUM('pending','active','paused','cancelled','expired') NOT NULL DEFAULT 'pending',
  starts_on      DATE         NOT NULL,
  -- Moves forward every time a day is skipped, which is the whole promise of
  -- "skip a day and your plan extends".
  ends_on        DATE         NOT NULL,
  delivery_slot  VARCHAR(32)  NULL,
  price_paid     DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes          TEXT,
  cancelled_at   DATETIME     NULL,
  cancel_reason  VARCHAR(255) NULL,
  created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at     DATETIME     NULL,
  KEY sub_user_idx (user_id, status),
  KEY sub_window_idx (starts_on, ends_on),
  KEY sub_status_idx (status),
  CONSTRAINT sub_user_fk    FOREIGN KEY (user_id)    REFERENCES users(id),
  CONSTRAINT sub_plan_fk    FOREIGN KEY (plan_id)    REFERENCES plans(id),
  CONSTRAINT sub_outlet_fk  FOREIGN KEY (outlet_id)  REFERENCES outlets(id),
  CONSTRAINT sub_address_fk FOREIGN KEY (address_id) REFERENCES addresses(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- What is actually being delivered on each day of a subscription. A nightly job
-- turns tomorrow's rows into real orders, so production, delivery, stock and
-- the books all see subscriptions as ordinary orders.
CREATE TABLE IF NOT EXISTS subscription_schedule (
  id              CHAR(36) NOT NULL PRIMARY KEY,
  subscription_id CHAR(36) NOT NULL,
  scheduled_date  DATE     NOT NULL,
  slot            ENUM('breakfast','lunch','dinner','anytime') NOT NULL DEFAULT 'lunch',
  menu_item_id    CHAR(36) NULL,
  quantity        SMALLINT UNSIGNED NOT NULL DEFAULT 1,
  status          ENUM('planned','skipped','ordered','delivered','missed') NOT NULL DEFAULT 'planned',
  -- Set once the nightly job materialises this row into a real order.
  order_id        CHAR(36) NULL,
  created_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY sched_sub_date_slot_uk (subscription_id, scheduled_date, slot),
  KEY sched_date_idx (scheduled_date, status),
  CONSTRAINT sched_sub_fk   FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE,
  CONSTRAINT sched_item_fk  FOREIGN KEY (menu_item_id)    REFERENCES menu_items(id),
  CONSTRAINT sched_order_fk FOREIGN KEY (order_id)        REFERENCES orders(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- A pause is a RANGE; a skip (subscription_skips) is a single day. Both extend
-- the end date, and both need to be visible to the kitchen.
CREATE TABLE IF NOT EXISTS subscription_pauses (
  id              CHAR(36)     NOT NULL PRIMARY KEY,
  subscription_id CHAR(36)     NOT NULL,
  paused_from     DATE         NOT NULL,
  paused_to       DATE         NOT NULL,
  reason          VARCHAR(255) NULL,
  created_by      CHAR(36)     NULL,
  created_at      DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY sp_sub_idx (subscription_id, paused_from),
  CONSTRAINT sp_range_chk CHECK (paused_to >= paused_from),
  CONSTRAINT sp_sub_fk   FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE,
  CONSTRAINT sp_actor_fk FOREIGN KEY (created_by)      REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS subscription_invoices (
  id              CHAR(36)      NOT NULL PRIMARY KEY,
  subscription_id CHAR(36)      NOT NULL,
  invoice_no      VARCHAR(32)   NOT NULL UNIQUE,
  period_from     DATE          NOT NULL,
  period_to       DATE          NOT NULL,
  subtotal        DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_amount      DECIMAL(12,2) NOT NULL DEFAULT 0,
  total           DECIMAL(12,2) NOT NULL DEFAULT 0,
  status          ENUM('draft','issued','paid','void') NOT NULL DEFAULT 'draft',
  issued_at       DATETIME      NULL,
  paid_at         DATETIME      NULL,
  created_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY si_sub_idx (subscription_id, period_from),
  CONSTRAINT si_sub_fk FOREIGN KEY (subscription_id) REFERENCES subscriptions(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Link the existing per-day skips to a subscription now that one exists.
ALTER TABLE subscription_skips
  ADD COLUMN IF NOT EXISTS subscription_id CHAR(36) NULL AFTER order_id;

-- ═══════════════════════════════════════════════════════════════════════════
-- 2 · RECIPES - the backbone
--
-- Right now a menu item's macros are typed in by hand and its cost is unknown.
-- Once recipe_lines exist, BOTH come from the same rows, so the nutrition label
-- on the storefront and the margin in the sales report can never disagree.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS recipes (
  id            CHAR(36)      NOT NULL PRIMARY KEY,
  menu_item_id  CHAR(36)      NOT NULL UNIQUE,
  yield_qty     DECIMAL(10,3) NOT NULL DEFAULT 1,     -- portions this makes
  method        TEXT          NULL,
  prep_minutes  SMALLINT UNSIGNED NULL,
  is_active     TINYINT(1)    NOT NULL DEFAULT 1,
  created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT rec_item_fk FOREIGN KEY (menu_item_id) REFERENCES menu_items(id) ON DELETE CASCADE,
  CONSTRAINT rec_yield_chk CHECK (yield_qty > 0)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS recipe_lines (
  id            CHAR(36)      NOT NULL PRIMARY KEY,
  recipe_id     CHAR(36)      NOT NULL,
  ingredient_id CHAR(36)      NOT NULL,
  -- Quantity in the ingredient's own unit, for ONE yield_qty batch.
  quantity      DECIMAL(12,4) NOT NULL,
  -- Trim/cooking loss. 0.9 means you buy 1kg and 900g reaches the bowl.
  yield_factor  DECIMAL(5,3)  NOT NULL DEFAULT 1.000,
  note          VARCHAR(255)  NULL,
  UNIQUE KEY rl_recipe_ing_uk (recipe_id, ingredient_id),
  CONSTRAINT rl_recipe_fk FOREIGN KEY (recipe_id)     REFERENCES recipes(id) ON DELETE CASCADE,
  CONSTRAINT rl_ing_fk    FOREIGN KEY (ingredient_id) REFERENCES ingredients(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Food cost per portion, derived. Never store this - the moment an ingredient
-- price changes, a stored copy is a lie.
CREATE OR REPLACE VIEW recipe_costs AS
SELECT
  r.menu_item_id,
  r.id AS recipe_id,
  ROUND(SUM(rl.quantity / NULLIF(rl.yield_factor, 0) * i.cost_per_unit) / NULLIF(r.yield_qty, 0), 2) AS food_cost_per_portion,
  COUNT(rl.id) AS ingredient_count
FROM recipes r
JOIN recipe_lines rl ON rl.recipe_id = r.id
JOIN ingredients  i  ON i.id = rl.ingredient_id
WHERE r.is_active = 1
GROUP BY r.id, r.menu_item_id, r.yield_qty;

-- Margin per menu item: price against derived food cost.
CREATE OR REPLACE VIEW menu_item_margins AS
SELECT
  mi.id AS menu_item_id, mi.slug, mi.name, mi.price,
  rc.food_cost_per_portion,
  ROUND(mi.price - COALESCE(rc.food_cost_per_portion, 0), 2) AS gross_margin,
  CASE WHEN mi.price > 0 AND rc.food_cost_per_portion IS NOT NULL
       THEN ROUND((mi.price - rc.food_cost_per_portion) / mi.price * 100, 1) END AS margin_pct
FROM menu_items mi
LEFT JOIN recipe_costs rc ON rc.menu_item_id = mi.id
WHERE mi.deleted_at IS NULL;

-- ═══════════════════════════════════════════════════════════════════════════
-- 3 · PROCUREMENT
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS vendors (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  code          VARCHAR(32)  NOT NULL UNIQUE,
  name          VARCHAR(190) NOT NULL,
  contact_name  VARCHAR(160) NULL,
  phone         VARCHAR(32)  NULL,
  email         VARCHAR(190) NULL,
  address       TEXT         NULL,
  gstin         VARCHAR(20)  NULL,
  payment_terms VARCHAR(64)  NULL,
  is_active     TINYINT(1)   NOT NULL DEFAULT 1,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at    DATETIME     NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS purchase_orders (
  id           CHAR(36)      NOT NULL PRIMARY KEY,
  po_no        VARCHAR(32)   NOT NULL UNIQUE,
  vendor_id    CHAR(36)      NOT NULL,
  outlet_id    CHAR(36)      NOT NULL,
  status       ENUM('draft','sent','partially_received','received','cancelled') NOT NULL DEFAULT 'draft',
  expected_on  DATE          NULL,
  subtotal     DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_amount   DECIMAL(12,2) NOT NULL DEFAULT 0,
  total        DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes        TEXT          NULL,
  created_by   CHAR(36)      NULL,
  created_at   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY po_vendor_idx (vendor_id, status),
  CONSTRAINT po_vendor_fk FOREIGN KEY (vendor_id)  REFERENCES vendors(id),
  CONSTRAINT po_outlet_fk FOREIGN KEY (outlet_id)  REFERENCES outlets(id),
  CONSTRAINT po_actor_fk  FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS purchase_order_lines (
  id                CHAR(36)      NOT NULL PRIMARY KEY,
  purchase_order_id CHAR(36)      NOT NULL,
  ingredient_id     CHAR(36)      NOT NULL,
  quantity_ordered  DECIMAL(12,3) NOT NULL,
  quantity_received DECIMAL(12,3) NOT NULL DEFAULT 0,
  unit_cost         DECIMAL(12,2) NOT NULL,
  line_total        DECIMAL(12,2) NOT NULL,
  KEY pol_po_idx (purchase_order_id),
  CONSTRAINT pol_qty_chk CHECK (quantity_ordered > 0),
  CONSTRAINT pol_po_fk   FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id) ON DELETE CASCADE,
  CONSTRAINT pol_ing_fk  FOREIGN KEY (ingredient_id)     REFERENCES ingredients(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Goods receipt: what actually turned up, which is rarely exactly what was ordered.
CREATE TABLE IF NOT EXISTS goods_receipts (
  id                CHAR(36)     NOT NULL PRIMARY KEY,
  grn_no            VARCHAR(32)  NOT NULL UNIQUE,
  purchase_order_id CHAR(36)     NULL,
  vendor_id         CHAR(36)     NOT NULL,
  outlet_id         CHAR(36)     NOT NULL,
  received_on       DATE         NOT NULL,
  received_by       CHAR(36)     NULL,
  notes             TEXT         NULL,
  created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY grn_vendor_idx (vendor_id, received_on),
  CONSTRAINT grn_po_fk     FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
  CONSTRAINT grn_vendor_fk FOREIGN KEY (vendor_id)         REFERENCES vendors(id),
  CONSTRAINT grn_outlet_fk FOREIGN KEY (outlet_id)         REFERENCES outlets(id),
  CONSTRAINT grn_actor_fk  FOREIGN KEY (received_by)       REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS goods_receipt_lines (
  id                CHAR(36)      NOT NULL PRIMARY KEY,
  goods_receipt_id  CHAR(36)      NOT NULL,
  ingredient_id     CHAR(36)      NOT NULL,
  quantity          DECIMAL(12,3) NOT NULL,
  unit_cost         DECIMAL(12,2) NOT NULL,
  batch_code        VARCHAR(64)   NULL,
  -- Fresh food: knowing what expires when is the difference between wastage
  -- you planned for and wastage you discover.
  expires_on        DATE          NULL,
  -- The stock_movements row this created, so the ledger and the GRN agree.
  stock_movement_id CHAR(36)      NULL,
  KEY grl_grn_idx (goods_receipt_id),
  KEY grl_expiry_idx (expires_on),
  CONSTRAINT grl_grn_fk FOREIGN KEY (goods_receipt_id) REFERENCES goods_receipts(id) ON DELETE CASCADE,
  CONSTRAINT grl_ing_fk FOREIGN KEY (ingredient_id)    REFERENCES ingredients(id),
  CONSTRAINT grl_mv_fk  FOREIGN KEY (stock_movement_id) REFERENCES stock_movements(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vendor_invoices (
  id                CHAR(36)      NOT NULL PRIMARY KEY,
  vendor_id         CHAR(36)      NOT NULL,
  purchase_order_id CHAR(36)      NULL,
  goods_receipt_id  CHAR(36)      NULL,
  invoice_no        VARCHAR(64)   NOT NULL,
  invoice_date      DATE          NOT NULL,
  due_date          DATE          NULL,
  subtotal          DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_amount        DECIMAL(12,2) NOT NULL DEFAULT 0,
  total             DECIMAL(12,2) NOT NULL DEFAULT 0,
  -- Nothing is payable until PO, GRN and invoice agree: the three-way match.
  status            ENUM('received','matched','disputed','paid') NOT NULL DEFAULT 'received',
  paid_at           DATETIME      NULL,
  created_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at        DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY vi_vendor_invoice_uk (vendor_id, invoice_no),
  CONSTRAINT vi_vendor_fk FOREIGN KEY (vendor_id)         REFERENCES vendors(id),
  CONSTRAINT vi_po_fk     FOREIGN KEY (purchase_order_id) REFERENCES purchase_orders(id),
  CONSTRAINT vi_grn_fk    FOREIGN KEY (goods_receipt_id)  REFERENCES goods_receipts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ═══════════════════════════════════════════════════════════════════════════
-- 4 · PRODUCTION - what the kitchen has to cook today
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS production_plans (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  outlet_id     CHAR(36) NOT NULL,
  business_date DATE     NOT NULL,
  status        ENUM('draft','confirmed','in_progress','completed') NOT NULL DEFAULT 'draft',
  notes         TEXT     NULL,
  created_by    CHAR(36) NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY pp_outlet_date_uk (outlet_id, business_date),
  CONSTRAINT pp_outlet_fk FOREIGN KEY (outlet_id)  REFERENCES outlets(id),
  CONSTRAINT pp_actor_fk  FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS production_lines (
  id                 CHAR(36)      NOT NULL PRIMARY KEY,
  production_plan_id CHAR(36)      NOT NULL,
  menu_item_id       CHAR(36)      NOT NULL,
  -- Aggregated from confirmed orders + tomorrow's subscription schedule.
  quantity_required  DECIMAL(10,2) NOT NULL DEFAULT 0,
  quantity_produced  DECIMAL(10,2) NOT NULL DEFAULT 0,
  UNIQUE KEY pl_plan_item_uk (production_plan_id, menu_item_id),
  CONSTRAINT pl_plan_fk FOREIGN KEY (production_plan_id) REFERENCES production_plans(id) ON DELETE CASCADE,
  CONSTRAINT pl_item_fk FOREIGN KEY (menu_item_id)       REFERENCES menu_items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Kitchen order ticket: the physical slip, one per order.
CREATE TABLE IF NOT EXISTS kitchen_tickets (
  id           CHAR(36) NOT NULL PRIMARY KEY,
  ticket_no    VARCHAR(32) NOT NULL UNIQUE,
  order_id     CHAR(36) NOT NULL,
  outlet_id    CHAR(36) NOT NULL,
  station      ENUM('grill','salad','smoothie','packing','general') NOT NULL DEFAULT 'general',
  status       ENUM('queued','preparing','ready','served') NOT NULL DEFAULT 'queued',
  started_at   DATETIME NULL,
  completed_at DATETIME NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY kt_order_idx (order_id),
  KEY kt_status_idx (status, created_at),
  CONSTRAINT kt_order_fk  FOREIGN KEY (order_id)  REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT kt_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ═══════════════════════════════════════════════════════════════════════════
-- 5 · PAYMENTS, TAX & CUSTOMER INVOICES
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS tax_rates (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  code          VARCHAR(32)  NOT NULL UNIQUE,
  name          VARCHAR(120) NOT NULL,
  rate_pct      DECIMAL(5,2) NOT NULL,
  hsn_code      VARCHAR(16)  NULL,
  -- Restaurant food supply in India is 5% with no input tax credit; packaged
  -- goods differ. Keep the rule in a row, not in code.
  input_credit  TINYINT(1)   NOT NULL DEFAULT 0,
  effective_from DATE        NOT NULL,
  effective_to   DATE        NULL,
  is_active     TINYINT(1)   NOT NULL DEFAULT 1,
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payments (
  id             CHAR(36)      NOT NULL PRIMARY KEY,
  order_id       CHAR(36)      NULL,
  subscription_id CHAR(36)     NULL,
  user_id        CHAR(36)      NOT NULL,
  method         ENUM('razorpay','upi','card','netbanking','cod','wallet') NOT NULL DEFAULT 'razorpay',
  status         ENUM('created','authorized','captured','failed','refunded') NOT NULL DEFAULT 'created',
  amount         DECIMAL(12,2) NOT NULL,
  currency       CHAR(3)       NOT NULL DEFAULT 'INR',
  -- Razorpay's ids. Unique so a replayed webhook cannot double-credit an order.
  provider_order_id   VARCHAR(64) NULL,
  provider_payment_id VARCHAR(64) NULL UNIQUE,
  provider_signature  VARCHAR(255) NULL,
  failure_reason VARCHAR(255)  NULL,
  captured_at    DATETIME      NULL,
  created_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at     DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY pay_order_idx (order_id),
  KEY pay_user_idx (user_id, created_at),
  CONSTRAINT pay_amount_chk CHECK (amount >= 0),
  CONSTRAINT pay_order_fk FOREIGN KEY (order_id)        REFERENCES orders(id),
  CONSTRAINT pay_sub_fk   FOREIGN KEY (subscription_id) REFERENCES subscriptions(id),
  CONSTRAINT pay_user_fk  FOREIGN KEY (user_id)         REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS refunds (
  id          CHAR(36)      NOT NULL PRIMARY KEY,
  payment_id  CHAR(36)      NOT NULL,
  order_id    CHAR(36)      NULL,
  amount      DECIMAL(12,2) NOT NULL,
  reason      VARCHAR(255)  NULL,
  status      ENUM('pending','processed','failed') NOT NULL DEFAULT 'pending',
  provider_refund_id VARCHAR(64) NULL,
  created_by  CHAR(36)      NULL,
  created_at  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processed_at DATETIME     NULL,
  KEY ref_payment_idx (payment_id),
  CONSTRAINT ref_amount_chk CHECK (amount > 0),
  CONSTRAINT ref_pay_fk   FOREIGN KEY (payment_id) REFERENCES payments(id),
  CONSTRAINT ref_order_fk FOREIGN KEY (order_id)   REFERENCES orders(id),
  CONSTRAINT ref_actor_fk FOREIGN KEY (created_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoices (
  id            CHAR(36)      NOT NULL PRIMARY KEY,
  invoice_no    VARCHAR(32)   NOT NULL UNIQUE,
  order_id      CHAR(36)      NULL,
  user_id       CHAR(36)      NOT NULL,
  outlet_id     CHAR(36)      NOT NULL,
  business_date DATE          NOT NULL,
  subtotal      DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_amount    DECIMAL(12,2) NOT NULL DEFAULT 0,
  total         DECIMAL(12,2) NOT NULL DEFAULT 0,
  gstin         VARCHAR(20)   NULL,
  status        ENUM('draft','issued','paid','cancelled') NOT NULL DEFAULT 'issued',
  issued_at     DATETIME      NULL,
  created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY inv_date_idx (business_date),
  CONSTRAINT inv_order_fk  FOREIGN KEY (order_id)  REFERENCES orders(id),
  CONSTRAINT inv_user_fk   FOREIGN KEY (user_id)   REFERENCES users(id),
  CONSTRAINT inv_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoice_lines (
  id           CHAR(36)      NOT NULL PRIMARY KEY,
  invoice_id   CHAR(36)      NOT NULL,
  description  VARCHAR(190)  NOT NULL,
  hsn_code     VARCHAR(16)   NULL,
  quantity     DECIMAL(10,2) NOT NULL DEFAULT 1,
  unit_price   DECIMAL(12,2) NOT NULL DEFAULT 0,
  tax_rate_pct DECIMAL(5,2)  NOT NULL DEFAULT 0,
  line_total   DECIMAL(12,2) NOT NULL DEFAULT 0,
  KEY il_invoice_idx (invoice_id),
  CONSTRAINT il_invoice_fk FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ═══════════════════════════════════════════════════════════════════════════
-- 6 · DELIVERY
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS delivery_zones (
  id            CHAR(36)      NOT NULL PRIMARY KEY,
  outlet_id     CHAR(36)      NOT NULL,
  name          VARCHAR(120)  NOT NULL,
  delivery_fee  DECIMAL(12,2) NOT NULL DEFAULT 0,
  free_above    DECIMAL(12,2) NULL,
  eta_minutes   SMALLINT UNSIGNED NOT NULL DEFAULT 30,
  is_active     TINYINT(1)    NOT NULL DEFAULT 1,
  created_at    DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT dz_outlet_fk FOREIGN KEY (outlet_id) REFERENCES outlets(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS delivery_zone_pincodes (
  zone_id CHAR(36)    NOT NULL,
  pincode VARCHAR(12) NOT NULL,
  PRIMARY KEY (zone_id, pincode),
  KEY dzp_pincode_idx (pincode),
  CONSTRAINT dzp_zone_fk FOREIGN KEY (zone_id) REFERENCES delivery_zones(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS delivery_assignments (
  id            CHAR(36) NOT NULL PRIMARY KEY,
  order_id      CHAR(36) NOT NULL,
  rider_id      CHAR(36) NULL,
  zone_id       CHAR(36) NULL,
  status        ENUM('unassigned','assigned','picked_up','delivered','failed') NOT NULL DEFAULT 'unassigned',
  assigned_at   DATETIME NULL,
  picked_up_at  DATETIME NULL,
  delivered_at  DATETIME NULL,
  failure_reason VARCHAR(255) NULL,
  proof_note    VARCHAR(255) NULL,
  created_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at    DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY da_order_uk (order_id),
  KEY da_rider_idx (rider_id, status),
  CONSTRAINT da_order_fk FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
  CONSTRAINT da_rider_fk FOREIGN KEY (rider_id) REFERENCES users(id),
  CONSTRAINT da_zone_fk  FOREIGN KEY (zone_id)  REFERENCES delivery_zones(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ═══════════════════════════════════════════════════════════════════════════
-- 7 · NUTRITION - the differentiator competitors can't copy by cutting prices
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS customer_profiles (
  user_id        CHAR(36) NOT NULL PRIMARY KEY,
  goal           ENUM('lose_fat','maintain','build_muscle','general_health') NULL,
  activity_level ENUM('sedentary','light','moderate','active','athlete') NULL,
  height_cm      DECIMAL(5,1) NULL,
  weight_kg      DECIMAL(5,1) NULL,
  date_of_birth  DATE     NULL,
  dietary_prefs  JSON     NULL,
  allergies      JSON     NULL,
  updated_at     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT cp_user_fk FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS macro_targets (
  id            CHAR(36)     NOT NULL PRIMARY KEY,
  user_id       CHAR(36)     NOT NULL,
  effective_from DATE        NOT NULL,
  calories      DECIMAL(8,2) NOT NULL DEFAULT 0,
  protein_g     DECIMAL(8,2) NOT NULL DEFAULT 0,
  carbs_g       DECIMAL(8,2) NOT NULL DEFAULT 0,
  fat_g         DECIMAL(8,2) NOT NULL DEFAULT 0,
  set_by        CHAR(36)     NULL,          -- a dietitian, or the customer
  created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY mt_user_from_uk (user_id, effective_from),
  CONSTRAINT mt_user_fk  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT mt_actor_fk FOREIGN KEY (set_by)  REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS meal_logs (
  id           CHAR(36)     NOT NULL PRIMARY KEY,
  user_id      CHAR(36)     NOT NULL,
  logged_on    DATE         NOT NULL,
  slot         ENUM('breakfast','lunch','dinner','snack') NOT NULL DEFAULT 'lunch',
  menu_item_id CHAR(36)     NULL,
  description  VARCHAR(190) NULL,
  calories     DECIMAL(8,2) NOT NULL DEFAULT 0,
  protein_g    DECIMAL(8,2) NOT NULL DEFAULT 0,
  carbs_g      DECIMAL(8,2) NOT NULL DEFAULT 0,
  fat_g        DECIMAL(8,2) NOT NULL DEFAULT 0,
  created_at   DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  KEY ml_user_date_idx (user_id, logged_on),
  CONSTRAINT ml_user_fk FOREIGN KEY (user_id)      REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT ml_item_fk FOREIGN KEY (menu_item_id) REFERENCES menu_items(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS consultations (
  id           CHAR(36) NOT NULL PRIMARY KEY,
  user_id      CHAR(36) NOT NULL,
  dietitian_id CHAR(36) NULL,
  scheduled_at DATETIME NOT NULL,
  duration_min SMALLINT UNSIGNED NOT NULL DEFAULT 30,
  status       ENUM('requested','confirmed','completed','cancelled','no_show') NOT NULL DEFAULT 'requested',
  notes        TEXT     NULL,
  created_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY con_user_idx (user_id, scheduled_at),
  CONSTRAINT con_user_fk FOREIGN KEY (user_id)      REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT con_diet_fk FOREIGN KEY (dietitian_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ═══════════════════════════════════════════════════════════════════════════
-- 8 · PERMISSIONS for the new areas
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO permissions (`key`, description) VALUES
  ('subscriptions.read',  'View subscriptions and their schedules'),
  ('subscriptions.write', 'Create, pause, resume and cancel subscriptions'),
  ('recipes.read',        'View recipes and food cost'),
  ('recipes.write',       'Edit recipes'),
  ('production.read',     'View the daily production plan'),
  ('production.write',    'Confirm production and kitchen tickets'),
  ('delivery.assign',     'Assign orders to riders'),
  ('nutrition.read',      'View customer goals and macro targets'),
  ('nutrition.write',     'Set macro targets and record consultations')
ON DUPLICATE KEY UPDATE description = VALUES(description);

INSERT IGNORE INTO role_permissions (role, permission_key) VALUES
  ('kitchen_staff','production.read'), ('kitchen_staff','production.write'),
  ('kitchen_staff','recipes.read'),    ('kitchen_staff','subscriptions.read'),

  ('delivery_rider','delivery.assign'),

  ('dietitian','nutrition.read'), ('dietitian','nutrition.write'),
  ('dietitian','recipes.read'),   ('dietitian','subscriptions.read'),

  ('inventory_manager','recipes.read'), ('inventory_manager','recipes.write'),
  ('inventory_manager','production.read'),

  ('accountant','subscriptions.read'),

  ('store_manager','subscriptions.read'), ('store_manager','subscriptions.write'),
  ('store_manager','recipes.read'),       ('store_manager','recipes.write'),
  ('store_manager','production.read'),    ('store_manager','production.write'),
  ('store_manager','delivery.assign'),    ('store_manager','nutrition.read'),

  ('owner','subscriptions.read'), ('owner','subscriptions.write'),
  ('owner','recipes.read'),       ('owner','recipes.write'),
  ('owner','production.read'),    ('owner','production.write'),
  ('owner','delivery.assign'),    ('owner','nutrition.read'), ('owner','nutrition.write');

-- ═══════════════════════════════════════════════════════════════════════════
-- 9 · SEED - the minimum that makes the new sections usable
-- ═══════════════════════════════════════════════════════════════════════════

INSERT INTO plans (id, slug, name, description, billing_period, meals_per_day, days_included, price, discount_pct, sort_order)
VALUES
 (UUID(),'weekly-flex','Weekly Flex','7 days, 1 meal a day, skip any day and the plan extends','weekly',1,7,1050.00,15.00,10),
 (UUID(),'weekly-pro','Weekly Pro','7 days, 2 meals a day for serious training weeks','weekly',2,7,1990.00,20.00,20),
 (UUID(),'monthly-flex','Monthly Flex','30 days, 1 meal a day, best value','monthly',1,30,4200.00,25.00,30),
 (UUID(),'monthly-pro','Monthly Pro','30 days, 2 meals a day, with dietitian check-ins','monthly',2,30,7900.00,30.00,40)
ON DUPLICATE KEY UPDATE name = VALUES(name), price = VALUES(price), description = VALUES(description);

INSERT INTO tax_rates (id, code, name, rate_pct, hsn_code, input_credit, effective_from)
VALUES
 (UUID(),'GST-5-FOOD','GST 5% - restaurant food supply (no ITC)',5.00,'996331',0,'2026-01-01'),
 (UUID(),'GST-12-PKG','GST 12% - packaged food',12.00,'2106',1,'2026-01-01'),
 (UUID(),'GST-18-SVC','GST 18% - services',18.00,'9963',1,'2026-01-01'),
 (UUID(),'GST-0-FRESH','GST 0% - fresh produce',0.00,'0709',0,'2026-01-01')
ON DUPLICATE KEY UPDATE name = VALUES(name), rate_pct = VALUES(rate_pct);

INSERT INTO vendors (id, code, name, contact_name, phone, payment_terms)
VALUES
 (UUID(),'VEN-FARM','FarmFresh Supplies','Ravi Kumar','+91 98450 11223','Net 15'),
 (UUID(),'VEN-HERI','Heritage Dairy','Sunita Rao','+91 98450 22334','Net 7'),
 (UUID(),'VEN-ORGT','Organic Traders','Imran Shaikh','+91 98450 33445','Net 30'),
 (UUID(),'VEN-GRNL','GreenLeaf Farms','Latha M','+91 98450 44556','Net 7'),
 (UUID(),'VEN-NUTR','NutriSource','Arjun Nair','+91 98450 55667','Advance')
ON DUPLICATE KEY UPDATE name = VALUES(name), contact_name = VALUES(contact_name);

INSERT INTO delivery_zones (id, outlet_id, name, delivery_fee, free_above, eta_minutes)
SELECT UUID(), o.id, z.name, z.fee, 499.00, z.eta
  FROM outlets o
  JOIN (SELECT 'Koramangala' AS name, 29.00 AS fee, 30 AS eta
        UNION ALL SELECT 'Indiranagar', 29.00, 35
        UNION ALL SELECT 'HSR Layout', 39.00, 40
        UNION ALL SELECT 'Bellandur', 49.00, 45
        UNION ALL SELECT 'Whitefield', 59.00, 55) z
 WHERE o.code = 'BKL-BLR-01'
   AND NOT EXISTS (SELECT 1 FROM delivery_zones dz WHERE dz.outlet_id = o.id AND dz.name = z.name);

INSERT IGNORE INTO delivery_zone_pincodes (zone_id, pincode)
SELECT dz.id, p.pincode FROM delivery_zones dz
  JOIN (SELECT 'Koramangala' AS zname, '560095' AS pincode
        UNION ALL SELECT 'Koramangala','560034'
        UNION ALL SELECT 'Indiranagar','560038'
        UNION ALL SELECT 'HSR Layout','560102'
        UNION ALL SELECT 'Bellandur','560103'
        UNION ALL SELECT 'Whitefield','560066') p ON p.zname = dz.name;

-- ═══════════════════════════════════════════════════════════════════════════
-- Verification
-- ═══════════════════════════════════════════════════════════════════════════

SELECT 'plans' AS item, COUNT(*) AS rows_now FROM plans
UNION ALL SELECT 'tax_rates',      COUNT(*) FROM tax_rates
UNION ALL SELECT 'vendors',        COUNT(*) FROM vendors
UNION ALL SELECT 'delivery_zones', COUNT(*) FROM delivery_zones
UNION ALL SELECT 'zone_pincodes',  COUNT(*) FROM delivery_zone_pincodes
UNION ALL SELECT 'permissions',    COUNT(*) FROM permissions
UNION ALL SELECT 'role_permissions', COUNT(*) FROM role_permissions
UNION ALL SELECT 'tables in schema', COUNT(*) FROM information_schema.tables
   WHERE table_schema = DATABASE() AND table_type = 'BASE TABLE';
