/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as R404RouteImport } from './routes/404'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CustomBowlRouteImport } from './routes/custom-bowl'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MyMacrosRouteImport } from './routes/my-macros'
import { Route as OpsConsoleRouteImport } from './routes/ops-console'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as AdminSplatRouteImport } from './routes/admin.$'
import { Route as OpsConsoleSplatRouteImport } from './routes/ops-console.$'
import { Route as ProductHandleRouteImport } from './routes/product.$handle'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomBowlRoute = CustomBowlRouteImport.update({
  id: '/custom-bowl',
  path: '/custom-bowl',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MyMacrosRoute = MyMacrosRouteImport.update({
  id: '/my-macros',
  path: '/my-macros',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsConsoleRoute = OpsConsoleRouteImport.update({
  id: '/ops-console',
  path: '/ops-console',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const OpsConsoleSplatRoute = OpsConsoleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => OpsConsoleRoute,
} as any)
const ProductHandleRoute = ProductHandleRouteImport.update({
  id: '/product/$handle',
  path: '/product/$handle',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/custom-bowl': typeof CustomBowlRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/my-macros': typeof MyMacrosRoute
  '/ops-console': typeof OpsConsoleRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/admin/$': typeof AdminSplatRoute
  '/ops-console/$': typeof OpsConsoleSplatRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/custom-bowl': typeof CustomBowlRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/my-macros': typeof MyMacrosRoute
  '/ops-console': typeof OpsConsoleRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/admin/$': typeof AdminSplatRoute
  '/ops-console/$': typeof OpsConsoleSplatRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/404': typeof R404Route
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/custom-bowl': typeof CustomBowlRoute
  '/kitchen': typeof KitchenRoute
  '/menu': typeof MenuRoute
  '/my-macros': typeof MyMacrosRoute
  '/ops-console': typeof OpsConsoleRouteWithChildren
  '/subscriptions': typeof SubscriptionsRoute
  '/admin/$': typeof AdminSplatRoute
  '/ops-console/$': typeof OpsConsoleSplatRoute
  '/product/$handle': typeof ProductHandleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/404'
    | '/account'
    | '/admin'
    | '/categories'
    | '/custom-bowl'
    | '/kitchen'
    | '/menu'
    | '/my-macros'
    | '/ops-console'
    | '/subscriptions'
    | '/admin/$'
    | '/ops-console/$'
    | '/product/$handle'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/404'
    | '/account'
    | '/admin'
    | '/categories'
    | '/custom-bowl'
    | '/kitchen'
    | '/menu'
    | '/my-macros'
    | '/ops-console'
    | '/subscriptions'
    | '/admin/$'
    | '/ops-console/$'
    | '/product/$handle'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/404'
    | '/account'
    | '/admin'
    | '/categories'
    | '/custom-bowl'
    | '/kitchen'
    | '/menu'
    | '/my-macros'
    | '/ops-console'
    | '/subscriptions'
    | '/admin/$'
    | '/ops-console/$'
    | '/product/$handle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  R404Route: typeof R404Route
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  CustomBowlRoute: typeof CustomBowlRoute
  KitchenRoute: typeof KitchenRoute
  MenuRoute: typeof MenuRoute
  MyMacrosRoute: typeof MyMacrosRoute
  OpsConsoleRoute: typeof OpsConsoleRouteWithChildren
  SubscriptionsRoute: typeof SubscriptionsRoute
  ProductHandleRoute: typeof ProductHandleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-bowl': {
      id: '/custom-bowl'
      path: '/custom-bowl'
      fullPath: '/custom-bowl'
      preLoaderRoute: typeof CustomBowlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-macros': {
      id: '/my-macros'
      path: '/my-macros'
      fullPath: '/my-macros'
      preLoaderRoute: typeof MyMacrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-console': {
      id: '/ops-console'
      path: '/ops-console'
      fullPath: '/ops-console'
      preLoaderRoute: typeof OpsConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$': {
      id: '/admin/$'
      path: '/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ops-console/$': {
      id: '/ops-console/$'
      path: '/$'
      fullPath: '/ops-console/$'
      preLoaderRoute: typeof OpsConsoleSplatRouteImport
      parentRoute: typeof OpsConsoleRoute
    }
    '/product/$handle': {
      id: '/product/$handle'
      path: '/product/$handle'
      fullPath: '/product/$handle'
      preLoaderRoute: typeof ProductHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OpsConsoleRouteChildren {
  OpsConsoleSplatRoute: typeof OpsConsoleSplatRoute
}

const OpsConsoleRouteChildren: OpsConsoleRouteChildren = {
  OpsConsoleSplatRoute: OpsConsoleSplatRoute,
}

const OpsConsoleRouteWithChildren = OpsConsoleRoute._addFileChildren(
  OpsConsoleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  R404Route: R404Route,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  CustomBowlRoute: CustomBowlRoute,
  KitchenRoute: KitchenRoute,
  MenuRoute: MenuRoute,
  MyMacrosRoute: MyMacrosRoute,
  OpsConsoleRoute: OpsConsoleRouteWithChildren,
  SubscriptionsRoute: SubscriptionsRoute,
  ProductHandleRoute: ProductHandleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
